apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jw3u9x0u6-go
  janus-idp.io/tekton: jw3u9x0u6-go
  backstage.io/kubernetes-id: jw3u9x0u6-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jw3u9x0u6-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
