apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jw3u9x0u6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jw3u9x0u6-go 
  name: jw3u9x0u6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jw3u9x0u6-go 
